### ISSUE TITLE
[BUG] Visualisation glitch on `MarkdownString` components

### ISSUE THREAD

**Issue by jlopezpena** [zenml-io/zenml-dashboard#590] opened 2024-05-07 09:57 UTC
One of my steps saves an artifact which is a `MarkdownString` element, using the `StructuredString` materialiser. In the visualisation, the background and the text color are almost identical, making it almost impossible to read the text.

This is how the visualization looks like:
<img width="972" alt="image" src="https://github.com/zenml-io/zenml-dashboard/assets/3518950/ca26b4c2-c39c-4916-b0a8-3369fadd660e">

The text can be read when selected, but looks invisible in the default view: 
<img width="981" alt="image" src="https://github.com/zenml-io/zenml-dashboard/assets/3518950/dbb13f3d-39bf-4543-b59b-49c3046f2870">

**Comment by Cahllagerfeld** [comment] 2024-05-07 10:07
Nice catch!

This looks like an issue with CSS.
Is this just affecting code blocks? Or does it also apply to regular text?

**Comment by Cahllagerfeld** [comment] 2024-05-07 10:44
I was able to reproduce it, for me it only happens in codeblocks

**Comment by Cahllagerfeld** [comment] 2024-05-27 07:55
As the PR was merged already, I would consider this Issue as closed 👍

**Closed by Cahllagerfeld** 2024-05-27 07:55 UTC
